# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RcQNfzmrykTv4XhuMBOZZS2_TlOGBb9h
"""

from textblob import TextBlob
import matplotlib.pyplot as plt

# Sample social media conversations (tweets/comments)
social_media_texts = [
    "I love the new features in this app!",
    "I'm so tired of this weather.",
    "What a beautiful day!",
    "This is the worst update ever.",
    "Feeling okay, nothing special today.",
    "Just had the best coffee of my life!",
    "So frustrated with the traffic jam.",
    "It's a normal day, I guess."
]

# Sentiment Analysis
sentiments = {"positive": 0, "neutral": 0, "negative": 0}

print("Sentiment Analysis Results:\n")

for i, text in enumerate(social_media_texts):
    blob = TextBlob(text)
    polarity = blob.sentiment.polarity  # range from -1 (neg) to +1 (pos)

    if polarity > 0.1:
        sentiment = "positive"
    elif polarity < -0.1:
        sentiment = "negative"
    else:
        sentiment = "neutral"

    sentiments[sentiment] += 1
    print(f"{i+1}. \"{text}\" => Sentiment: {sentiment} (Polarity: {polarity:.2f})")

# Displaying sentiment distribution
labels = sentiments.keys()
values = sentiments.values()

plt.bar(labels, values, color=['green', 'gray', 'red'])
plt.title("Sentiment Distribution of Social Media Conversations")
plt.xlabel("Sentiment")
plt.ylabel("Number of Conversations")
plt.show()